services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/FastAPI/Dockerfile
    container_name: fastapi
    volumes:
      - ../app:/app
      - ../tests:/tests
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY_TOKEN: ${SECRET_KEY_TOKEN}
      ALGORITHM_TOKEN: ${ALGORITHM_TOKEN}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      postgres:
        condition: service_healthy
